receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - http://*
            - https://*

exporters:
  zipkin:
    endpoint: 'http://zipkin:9411/api/v2/spans'
    format: json

processors:
  batch:
    send_batch_size: 512
    send_batch_max_size: 1024
    timeout: 5s

service:
  telemetry:
    logs:
      level: 'debug'
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
      processors: [batch]
