name: CD-Sonar Metrics Collector

on:
  workflow_dispatch: 
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: NPM install and build
        run: |
          npm install
          npm run build

      - name: Deploy-ssh
        run: |
          ssh-keyscan -t rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd db1-projects/sonar-metrics-collector/;
            docker container stop sonar-metrics-collector || true;
            docker rm sonar-metrics-collector || true;
            git pull origin main;
            docker rmi sonar-metrics-collector || true;
            docker build -t sonar-metrics-collector .;
            docker run -d -t -i -e npm run start:prod -p 5100:5100 --name sonar-metrics-collector sonar-metrics-collector;
